EventStore.Web/Models/LoginDetailsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventStore.Common;

namespace EventStore.Web.Models
{
    public class LoginDetailsModel
    {
        public string Username { get; set; }
        public List<Login> Logins { get; set; }
    }
}

EventStore.Web/Models/LoginHistoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventStore.Common;

namespace EventStore.Web.Models
{
    public class LoginHistoryModel
    {
        public List<Login> Logins { get; set; }
    }
}

EventStore.Web/Models/ViewCollectionsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventStore.Web.Models
{
    public class ViewCollectionsModel
    {
        public List<string> Collections { get; set; }

        public ViewCollectionsModel()
        {
            Collections = new List<string>();
        }
    }
}

EventStore.Web/Models/ViewEntitiesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventStore.Common;

namespace EventStore.Web.Models
{
    public class ViewEntitiesModel
    {
        public int PageNumber { get; set; }
        public string CollectionName { get; set; }
        public List<Hospital> Hospitals { get; set; }
    }
}

EventStore.Web/Models/ViewEntityDetailsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventStore.Common;

namespace EventStore.Web.Models
{
    public class ViewEntityDetailsModel
    {
        public string CollectionName { get; set; }
        public Hospital HospitalDetails { get; set; }
    }
}

EventStore.Web/Models/ViewHistoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EventStore.Common;

namespace EventStore.Web.Models
{
    public class ViewHistoryModel
    {
        public string HospitalId { get; set; }
        public string CollectionName { get; set; }
        public Hospital Current { get; set; }
        public List<Hospital> HospitalHistory { get; set; } 
    }
}

EventStore.Web/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EventStore.Common;
using EventStore.Data;
using EventStore.Web.Models;
using MongoDB.Driver;
using MongoDB.Driver.Linq;

namespace EventStore.Web.Controllers
{
    public class DetailsController : Controller
    {
        private string DefaultEntityId = "55281c633b43353f608aceda";
        private int PageSize = 100;

        public ActionResult ViewCollections()
        {
            ViewCollectionsModel model = new ViewCollectionsModel();

            var mongo = GetMongoDb();
            var results = mongo.ListCollectionsAsync().Result.ToListAsync().Result;

            foreach (var result in results)
            {
                string name = result["name"].ToString();

                if (name != "system.indexes")
                {
                    model.Collections.Add(name);
                }
            }

            return View(model);
        }

        public ActionResult ViewEntities(string CollectionName, int Page = 0)
        {
            int skip = 0;

            if (CollectionName == null)
            {
                CollectionName = "EventStore.Common.Hospital";
            }

            ViewEntitiesModel model = new ViewEntitiesModel();

            var mongo = GetMongoDb();
            IMongoCollection<Hospital> collection = mongo.GetCollection<Hospital>(CollectionName);
            var results = collection.FindAsync(x => x.Id != null);
            results.Wait();

            var docs = results.Result.ToListAsync();
            docs.Wait();

            model.Hospitals = docs.Result.Skip(skip).Take(PageSize).ToList();
            model.CollectionName = CollectionName;

            return View(model);
        }

        public ActionResult ViewEntityDetails(string CollectionName, string EntityId)
        {
            ViewEntityDetailsModel model = new ViewEntityDetailsModel();

            model.HospitalDetails = getEntity(CollectionName, EntityId);
            model.CollectionName = CollectionName;

            return View(model);
        }

        private Hospital getEntity(string CollectionName, string EntityId)
        {
            if (CollectionName == null)
            {
                CollectionName = "EventStore.Common.Hospital";
            }

            if (EntityId == null)
            {
                EntityId = this.DefaultEntityId;
            }

            var mongo = GetMongoDb();
            IMongoCollection<Hospital> collection = mongo.GetCollection<Hospital>(CollectionName);
            var results = collection.FindAsync(x => x.Id == EntityId);
            results.Wait();

            var docs = results.Result.ToListAsync();
            docs.Wait();

            return docs.Result.FirstOrDefault();
        }

        public ActionResult History(string CollectionName, string EntityId)
        {
            if (CollectionName == null)
            {
                CollectionName = "EventStore.Common.Hospital";
            }

            if (EntityId == null)
            {
                EntityId = this.DefaultEntityId;
            }

            ViewHistoryModel model = new ViewHistoryModel();

            Hospital current = getEntity(CollectionName, EntityId);
            DataManager<Hospital> dataManager = new DataManager<Hospital>();

            var historyItems = dataManager.GetHistory(current);

            model.HospitalId = EntityId;
            model.HospitalHistory = historyItems.ToList();
            model.Current = current;
            model.CollectionName = CollectionName;

            return View(model);
        }

        public ActionResult LoginHistory()
        {
            LoginHistoryModel model = new LoginHistoryModel();

            var mongo = GetMongoDb();
            IMongoCollection<Login> collection = mongo.GetCollection<Login>("EventStore.Common.Login");
            var results = collection.FindAsync(x => x.Id != null);
            results.Wait();

            var docs = results.Result.ToListAsync();
            docs.Wait();

            model.Logins = docs.Result.ToList();

            return View(model);
        }

        public ActionResult LoginDetails(string Username)
        {
            LoginDetailsModel model = new LoginDetailsModel();

            var mongo = GetMongoDb();
            IMongoCollection<Login> collection = mongo.GetCollection<Login>("EventStore.Common.Login");
            var results = collection.FindAsync(x => x.UserName == Username);
            results.Wait();

            var docs = results.Result.ToListAsync();
            docs.Wait();

            DataManager<Login> dataManager = new DataManager<Login>();
            var historyItems = dataManager.GetHistory(docs.Result.First());

            model.Logins = historyItems.ToList();
            model.Username = Username;

            return View(model);
        }

        private IMongoDatabase GetMongoDb()
        {
            var client = new MongoClient();
            var db = client.GetDatabase("EventStore");
            return db;
        }
	}
}

EventStore.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventStore.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Links()
        {
            return View();
        }
    }
}

EventStore.Web/Views/Details/History.cshtml
@model EventStore.Web.Models.ViewHistoryModel

@{
    ViewBag.Title = "View Entity History";
}

<br />

<table cellpadding="15px">

    <tr>
        <td></td>
        <td>Historical Value</td>
        <td>Current Value</td>
    </tr>

    @foreach (var histItem in Model.HospitalHistory)
    {
        <tr
            @if (histItem.Id != Model.Current.Id)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Id: </strong></td>
            <td>@histItem.Id</td>
            <td>@Model.Current.Id</td>
        </tr>

        <tr
            @if (histItem.StreamId.ToString() != Model.Current.StreamId.ToString())
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Stream Id: </strong></td>
            <td>@histItem.StreamId.ToString()</td>
            <td>@Model.Current.StreamId.ToString()</td>
        </tr>

        <tr
            @if (histItem.HospitalId != Model.Current.HospitalId)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Hospital Id: </strong></td>
            <td>@histItem.HospitalId</td>
            <td>@Model.Current.HospitalId</td>
        </tr>

        <tr
            @if (histItem.Name != Model.Current.Name)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Name: </strong></td>
            <td>@histItem.Name</td>
            <td>@Model.Current.Name</td>
        </tr>

        <tr
            @if (histItem.Address != Model.Current.Address)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Address: </strong></td>
            <td>@histItem.Address</td>
            <td>@Model.Current.Address</td>
        </tr>

        <tr
            @if (histItem.City != Model.Current.City)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>City: </strong></td>
            <td>@histItem.City</td>
            <td>@Model.Current.City</td>
        </tr>

        <tr
            @if (histItem.State != Model.Current.State)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>State: </strong></td>
            <td>@histItem.State</td>
            <td>@Model.Current.State</td>
        </tr>

        <tr
            @if (histItem.ZipCode != Model.Current.ZipCode)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>ZipCode: </strong></td>
            <td>@histItem.ZipCode</td>
            <td>@Model.Current.ZipCode</td>
        </tr>

        <tr
            @if (histItem.CountyName != Model.Current.CountyName)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>County: </strong></td>
            <td>@histItem.CountyName</td>
            <td>@Model.Current.CountyName</td>
        </tr>

        <tr
            @if (histItem.PhoneNumber != Model.Current.PhoneNumber)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Phone Number: </strong></td>
            <td>@histItem.PhoneNumber</td>
            <td>@Model.Current.PhoneNumber</td>
        </tr>

        <tr
            @if (histItem.Type != Model.Current.Type)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Type: </strong></td>
            <td>@histItem.Type</td>
            <td>@Model.Current.Type</td>
        </tr>

        <tr
            @if (histItem.Ownership != Model.Current.Ownership)
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Ownership: </strong></td>
            <td>@histItem.Ownership</td>
            <td>@Model.Current.Ownership</td>
        </tr>

        <tr
            @if (histItem.EmergencyServices.ToString() != Model.Current.EmergencyServices.ToString())
            {
                @:bgcolor="red"
            }
            >
            <td><strong>Emergency Services: </strong></td>
            <td>@histItem.EmergencyServices.ToString()</td>
            <td>@Model.Current.EmergencyServices.ToString()</td>
        </tr>

        <tr>
            <td><strong>Import Year: </strong></td>
            <td>@histItem.LastImportYear.ToString()</td>
            <td>@Model.Current.LastImportYear.ToString()</td>
        </tr>
        <tr>
            <td colspan="3">
                <hr />
            </td>
        </tr>
    }


    <tr>
        <td colspan="3">
            @Html.ActionLink("<< Back to entity detail", "ViewEntityDetails", new { CollectionName = "", EntityId = Model.Current.Id })
        </td>
    </tr>
</table>

EventStore.Web/Views/Details/LoginDetails.cshtml
@model EventStore.Web.Models.LoginDetailsModel

@{
    ViewBag.Title = "Login History";
}

<br />

<table cellpadding="15px">

    @foreach (var login in Model.Logins)
    {
        <tr>
            <td>
                @login.UserName
            </td>
            <td>
                @login.LastLogin
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
    }

</table>

EventStore.Web/Views/Details/LoginHistory.cshtml
@model EventStore.Web.Models.LoginHistoryModel

@{
    ViewBag.Title = "Login History";
}

<br />

<table cellpadding="15px">

    @foreach (var login in Model.Logins)
    {
        <tr>
            <td>
                @login.UserName
            </td>
            <td>
                @login.LastLogin
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
    }

</table>

EventStore.Web/Views/Details/ViewCollections.cshtml
@model EventStore.Web.Models.ViewCollectionsModel

@{
    ViewBag.Title = "View Collections";
}

<br />

<table cellpadding="15px">

    @foreach (var collectionName in Model.Collections)
    {
        <tr>
            <td>
                @collectionName
            </td>
            <td>
                @if (collectionName == "EventStore.Common.Login")
                {
                    @Html.ActionLink("View", "LoginHistory")
                }
                else
                {
                    @Html.ActionLink("View", "ViewEntities", new { CollectionName = collectionName })
                }
            </td>
        </tr>
    }

</table>

EventStore.Web/Views/Details/ViewEntities.cshtml
@model EventStore.Web.Models.ViewEntitiesModel

@{
    ViewBag.Title = "View Entities";
}

<br />

<table cellpadding="15px">

    @foreach (var hospital in Model.Hospitals)
    {
        <tr>
            <td>
                @hospital.Name
            </td>
            <td>
                @Html.ActionLink("View", "ViewEntityDetails", new { CollectionName = "", EntityId = hospital.Id })
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
    }

</table>

EventStore.Web/Views/Details/ViewEntityDetails.cshtml
@model EventStore.Web.Models.ViewEntityDetailsModel

@{
    ViewBag.Title = "View Entiy Details";
}

<br />

<table cellpadding="15px">

    <tr>
        <td colspan="2">
            @Html.ActionLink("View History", "History", new { CollectionName = "", EntityId = Model.HospitalDetails.Id })
        </td>
    </tr>

    <tr>
        <td><strong>Id: </strong></td>
        <td>@Model.HospitalDetails.Id</td>
    </tr>

    <tr>
        <td><strong>Stream Id: </strong></td>
        <td>@Model.HospitalDetails.StreamId.ToString()</td>
    </tr>

    <tr>
        <td><strong>Hospital Id: </strong></td>
        <td>@Model.HospitalDetails.HospitalId</td>
    </tr>

    <tr>
        <td><strong>Name: </strong></td>
        <td>@Model.HospitalDetails.Name</td>
    </tr>

    <tr>
        <td><strong>Address: </strong></td>
        <td>@Model.HospitalDetails.Address</td>
    </tr>

    <tr>
        <td><strong>City: </strong></td>
        <td>@Model.HospitalDetails.City</td>
    </tr>

    <tr>
        <td><strong>State: </strong></td>
        <td>@Model.HospitalDetails.State</td>
    </tr>

    <tr>
        <td><strong>ZipCode: </strong></td>
        <td>@Model.HospitalDetails.ZipCode</td>
    </tr>

    <tr>
        <td><strong>County: </strong></td>
        <td>@Model.HospitalDetails.CountyName</td>
    </tr>

    <tr>
        <td><strong>Phone Number: </strong></td>
        <td>@Model.HospitalDetails.PhoneNumber</td>
    </tr>

    <tr>
        <td><strong>Type: </strong></td>
        <td>@Model.HospitalDetails.Type</td>
    </tr>

    <tr>
        <td><strong>Ownership: </strong></td>
        <td>@Model.HospitalDetails.Ownership</td>
    </tr>

    <tr>
        <td><strong>Emergency Services: </strong></td>
        <td>@Model.HospitalDetails.EmergencyServices.ToString()</td>
    </tr>

    <tr>
        <td colspan="2">
            @Html.ActionLink("<< Back to collection", "ViewEntities", new { CollectionName = Model.CollectionName })
        </td>
    </tr>
</table>

EventStore.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>CQRS/Event Sourcing</h1>
    <p class="lead">CQRS stands for Command Query Responsibility Segregation. It's a pattern that I first heard described by Greg Young. At its heart is the notion that you can use a different model to update information than the model you use to read information. While this is more complex than is needed in most cases, it does fit well with a significant class of problems.</p>
    <p><a href="http://martinfowler.com/bliki/CQRS.html" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>View All Mongo Collections</h2>
        <p>
            Start this demo by viewing all the document collections in the Mongo instance.
        </p>
        <p>@Html.ActionLink("View Collections", "ViewCollections", "Details")</p>
    </div>
</div>

EventStore.Web/Views/Home/Links.cshtml

@{
    ViewBag.Title = "Links";
}
<br />
<strong>CQRS:</strong>
<ol>
    <li>
        <a href="http://martinfowler.com/bliki/CQRS.html">http://martinfowler.com/bliki/CQRS.html</a>
    </li>
    <li>
        <a href="https://msdn.microsoft.com/en-us/library/dn568103.aspx">https://msdn.microsoft.com/en-us/library/dn568103.aspx</a>
    </li>
    <li>
        <a href="https://msdn.microsoft.com/en-us/library/jj554200.aspx">https://msdn.microsoft.com/en-us/library/jj554200.aspx</a>
    </li>
    <li>
        <a href="http://en.wikipedia.org/wiki/Command%E2%80%93query_separation">http://en.wikipedia.org/wiki/Command%E2%80%93query_separation</a>
    </li>
    <li>
        <a href="http://abdullin.com/post/when-not-to-use-cqrs/">http://abdullin.com/post/when-not-to-use-cqrs/</a>
    </li>
</ol>
<br />
<strong>Event Sourcing:</strong>
<ol>
    <li>
        <a href="http://martinfowler.com/eaaDev/EventSourcing.html">http://martinfowler.com/eaaDev/EventSourcing.html</a>
    </li>
    <li>
        <a href="https://msdn.microsoft.com/en-us/library/dn589792.aspx">https://msdn.microsoft.com/en-us/library/dn589792.aspx</a>
    </li>
    <li>
        <a href="https://msdn.microsoft.com/en-us/library/jj591559.aspx">https://msdn.microsoft.com/en-us/library/jj591559.aspx</a>
    </li>
    <li>
        <a href="http://cqrs.nu/Faq/event-sourcing">http://cqrs.nu/Faq/event-sourcing</a>
    </li>
</ol>
<br />
<strong>Microservices:</strong>
<ol>
    <li>
        <a href="http://martinfowler.com/articles/microservices.html">http://martinfowler.com/articles/microservices.html</a>
    </li>
    <li>
        <a href="http://microservices.io/patterns/microservices.html">http://microservices.io/patterns/microservices.html</a>
    </li>
    <li>
        <a href="http://www.infoq.com/articles/microservices-intro">http://www.infoq.com/articles/microservices-intro</a>
    </li>
</ol>


EventStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CQRS/Event Sourcing Demo", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("View Collections", "ViewCollections", "Details")</li>
                    <li>@Html.ActionLink("Links", "Links", "Home")</li>
                    <li>@Html.ActionLink("Logins", "LoginHistory", "Details")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>